### ISSUE TITLE
大佬 协助下 输入yq > login+token 没反应 mcos 12

### ISSUE THREAD

**Issue by Mcurezhou** [wisinfun/Alfred-Workflow-yuque#1]
输入yq > login+token 没反应 mcos 12
![截屏2022-07-31 02 55 55](https://user-images.githubusercontent.com/110305801/181937773-8f397d10-5130-4b5f-ba5c-cdd4981b6ac7.png)
.

**Comment by wisinfun** [comment]
> 输入yq > login+token 没反应 mcos 12
> ![截屏2022-07-31 02 55 55](https://user-images.githubusercontent.com/110305801/181937773-8f397d10-5130-4b5f-ba5c-cdd4981b6ac7.png)
> .

尝试下小写`yq`

**Comment by wisinfun** [comment]
已经更新了新版，分享功能恢复，token直接在配置页里添加，可是尝试下

**Comment by Mcurezhou** [comment]
> 
![截屏2022-08-01 01 23 44](https://user-images.githubusercontent.com/110305801/182038693-c742f8a5-8b23-431f-8010-ecfb836d70e0.png)

非常感谢 但是看你之前的教程自己改过路径 我应该要改回来吧 非常感谢 你已经很用心了

**Comment by wisinfun** [comment]
> ![截屏2022-08-01 01 23 44](https://user-images.githubusercontent.com/110305801/182038693-c742f8a5-8b23-431f-8010-ecfb836d70e0.png)
> 
> 非常感谢 但是看你之前的教程自己改过路径 我应该要改回来吧 非常感谢 你已经很用心了

之前用的python脚本，现在换成node了，需要安装node，参考下新教程的配置步骤
