### ISSUE TITLE
增加了token，但是优先级不一样，跳转到另外一个搜索命令了

### ISSUE THREAD

**Issue by semi-xi** [wisinfun/Alfred-Workflow-yuque#2]
一开始输入12 都还是在羽雀的，但是好像是发现搜不到还是啥就跳转到了常规搜索了
<img width="719" alt="企业微信截图_c8ffeb65-3e78-45d6-b9af-6415446250fb" src="https://user-images.githubusercontent.com/7565129/201309425-ad9d82f1-ed5c-4b96-b95e-8abf8a0de7fb.png">

<img width="700" alt="企业微信截图_bba89646-db06-41d5-957a-ea8f5349ecb2" src="https://user-images.githubusercontent.com/7565129/201309665-68a880d8-4443-4b9b-a00e-4732afbad206.png">

**Comment by semi-xi** [comment]
感觉像是走了fallback搜索，搜不到，我看了下token那些都是正确的，node的版本是14

**Comment by wisinfun** [comment]
@semi-xi 调试模式看下
![image](https://user-images.githubusercontent.com/41355260/201375051-b33a419a-d8be-4c94-8207-69d80013b181.png)

**Comment by semi-xi** [comment]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/7565129/201861526-13539607-72e8-491d-ae93-7ad03f932455.png">
<img width="511" alt="image" src="https://user-images.githubusercontent.com/7565129/201861598-be589788-8568-445b-98ec-4edf671c1c06.png">
<img width="840" alt="image" src="https://user-images.githubusercontent.com/7565129/201863167-7445c8f5-d7a8-4b15-8bee-7b96b7a7b0ed.png">
@wisinfun

**Comment by wisinfun** [comment]
https://www.yuque.com/yuque/developer/high_level_api
这是语雀的 API ，你可以用 postman 或者其他类似工具测试下 token 是否能搜索到文档，或者把你的 Token 私发我
@semi-xi

**Comment by semi-xi** [comment]
![image](https://user-images.githubusercontent.com/7565129/201925598-b664adb9-3b32-4a6c-94de-44de41b7e23a.png)
我看了下置顶就写了不支持搜索私密哭，不知道跟这个有没有关系。我搜其他可以的。但是如果scope是自己的私密库就不行，你可以试下

**Comment by wisinfun** [comment]
应该不是这个原因，我可以搜索私密知识库的文档的

**Comment by semi-xi** [comment]
因为没有站内信，发不了token给你ORz
![image](https://user-images.githubusercontent.com/7565129/202085490-0ef522f4-ebff-46ee-acb9-4b6ab3f47c41.png)
![image](https://user-images.githubusercontent.com/7565129/202085928-0cbf0cb2-588f-4125-ae12-b301c5567459.png)

```
req：
url: https://www.yuque.com/api/v2/search?q=规范&type=doc&scope=ruzrfv
```
response
```
{
    "meta": {
        "total": 0
    },
    "data": []
}
```
postman的结果就是这样了

@wisinfun

**Comment by wisinfun** [comment]
@semi-xi 有postman测试就行了，看来还是语雀这边的问题，不知道为啥是这个 Token 获取不到文档
你的文档是在自己的用户下还是在空间里

**Comment by semi-xi** [comment]
> 

都是在空间的。你有没有邮箱，有的话我可以发个token给你试下。我这边是一直都不太行

**Comment by wisinfun** [comment]
@semi-xi  先不用，还没兼容空间的搜索，我先看看语雀的接口是否支持

**Comment by wisinfun** [comment]
试试新版本 @semi-xi

**Comment by semi-xi** [comment]
> 试试新版本 @semi-xi

用新版本就可以。thanks~是做了什么调整么，我之前postman也不行

**Comment by wisinfun** [comment]
主要是空间有独立的域名，所以 URL 不一致了
