### ISSUE TITLE
增加指定知识库搜索

### ISSUE THREAD

**Issue by semi-xi** [wisinfun/Alfred-Workflow-yuque#3]
在实际应用中，一个企业会有多个团队，这样就开了很多的一些知识库。但是常用的话其实只有自己的团队知识库，所以能不能只搜索某个知识库，或者某几个
![image](https://user-images.githubusercontent.com/7565129/203790385-a4cc8588-5957-4ed3-b654-b4c5676e0f0d.png)

**Comment by wisinfun** [comment]
增加个团队参数的筛选，是不是就满足了

**Comment by semi-xi** [comment]
> 

我觉得应该可以。支持多选？

**Comment by wisinfun** [comment]
@semi-xi 语雀的API貌似有bug，还无法实现这个需求，等语雀后续完善吧

**Comment by semi-xi** [comment]
我试了下，好像现在可以了。我自己试的时候是这样 
<img width="538" alt="image" src="https://user-images.githubusercontent.com/7565129/215473115-8b5b4474-818b-4c3c-8f0e-a2d149174d7e.png">
不过只能支持单个下面就是
